version: "3.7"

services:
  backend01:
    image: nginx
  backend02:
    image: nginx
  backend03:
    image: nginx
  reverse-proxy:
    build:
      context: .
    ports:
    - 9090:9090
    volumes:
    - "./config:/app/config"
