config:
  proxy address: "0.0.0.0:9090"

routes:
  /redirect:
    strategy: roundrobin
    root: true
    servers:
      - http://backend01:80
      - http://backend02:80
  /nginx:
    strategy: random
    root: false
    servers:
      - http://backend01:80
      - http://backend02:80
      - http://backend03:80
